package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"clean-arch/internal/infra/graph/model"
	"context"
	"strconv"
)

// ListOrders is the resolver for the listOrders field.
func (r *queryResolver) ListOrders(ctx context.Context) ([]*model.Order, error) {
	orders, err := r.OrderRepo.ListOrders()
	if err != nil {
		return nil, err
	}

	var result []*model.Order
	for _, o := range orders {
		orderModel := &model.Order{
			ID:          strconv.Itoa(o.ID),
			Description: o.Description,
			Price:       o.Price,
			CreatedAt:   o.CreatedAt.String(),
		}
		result = append(result, orderModel)
	}

	return result, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
